### ISSUE TITLE
After deploying the Flask server onto a VPS, it was observed that although users could successfully log in, retrieval of their information was unsuccessful

### ISSUE THREAD

**Issue by skyline88888888** [casdoor/casdoor-python-vue-sdk-example#11]
After deploying the Flask server onto a VPS, it was observed that although users could successfully log in, retrieval of their information was unsuccessful.

**Comment by hsluoyz** [comment]
@skyline88888888 can't you see this like README? show your video

![image](https://github.com/casdoor/casdoor-python-vue-sdk-example/assets/3787410/cdc2ca06-2f5a-4b4d-9caa-e41c424dc8da)

**Comment by skyline88888888** [comment]
I am able to access the webpage; however, the table is blank. My current process involves running the web directory locally and the root directory on the remote server. I believe the issue is with the session and not with the directories.

**Comment by hsluoyz** [comment]
@skyline88888888 try to run the code locally, if works, then it's your VPS issue. If still has issue, go to the QQ group

**Comment by skyline88888888** [comment]
> @skyline88888888 try to run the code locally, if works, then it's your VPS issue. If still has issue, go to the QQ group

Upon my local testing, the application ran without any issues. However, after deploying the server onto a vps, I encountered a problem where the browser failed to execute "set-cookie" correctly, causing userinfo to be unattainable. Despite this drawback, the server was still able to generate session.

**Comment by hsluoyz** [comment]
@skyline88888888 then this is your VPS's issue. I'm afraid we cannot provide useful help on your case. You should ask for help from your VPS customer support.
