### ISSUE TITLE
example fails

### ISSUE THREAD

**Issue by tetra12** [casdoor/casdoor-python-vue-sdk-example#6]
Following your instructions, I was able to do `SignUp`. When I try `SignIn` I'm getting the following:
![pic](https://user-images.githubusercontent.com/45828526/173245270-a4abbf61-ec96-417f-a03c-db9c26de3c04.png)

I'm using all default settings. In my app setup, I see only default Redirect URL `http://localhost:9000/callback`
My JS config:

```bash
const config = {
  serverUrl: "http://localhost:8000",
  clientId: "<clientID>",
  organizationName: "test",
  appName: "test-front",
  redirectPath: "/callback",
};
```

How do I setup my app to

**Comment by tetra12** [comment]
I found that my Casdoor `Test SignIn Page` doesn't work, returning this result. Still confused by this example, since an "example pet project" doesn't deliver any clear picture of using Casdoor SDK

**Comment by hsluoyz** [comment]
Hi @tetra12 the issues you created these days are mostly simple questions or not Casdoor issues. Plz stop making new issues and try to ask questions via channels like Gitter: https://casdoor.org/help

**Comment by tetra12** [comment]
@hsluoyz Hi you didn't answer any of my questions. The issue is THE issue. 

You can't make it work on YOUR OWN example ! How do you think other ppl would use it and move further than pet projects?

The support of your project is poor at best, getting closer to NON-EXISTENT. Do you develop your project so that only few fellow Chinese students could use it in their pet projects :thinking: ?

**Comment by y00rb** [comment]
@tetra12 you need set up a "Redirect URLs" on the Casdoor. "http://localhost:8080/callback" and "http://localhost:5000/api/signin" both exists in The Casdoor setting(Application on Casdoor). in this way, the "sign in" would be redirect to correctly URL.
